### ISSUE TITLE
AttributeError: 'MultipleSeqAlignment' object has no attribute 'add_sequence'

### ISSUE THREAD

**Issue by Irvilma** [tkchafin/vcf2msa.py#1]
Hello,

I would like to use this script to convert my vcf file. But I'm getting an error that I do not how I can solve. 

I'm working with Python 3.6.12 :: Anaconda, Inc.

I have installed all dependences with conda:
conda install -c bioconda biopython pyvcf pysam muscle

My command: python3 ./vcf2msa.py -r reference.fasta -v variants.vcf.gz

Found mask files: dict_keys([])
Traceback (most recent call last):
  File "./vcf2msa.py", line 559, in <module>
    main()
  File "./vcf2msa.py", line 179, in main
    this_pos = muscle_align(this_pos)
  File "./vcf2msa.py", line 271, in muscle_align
    records.add_sequence(key, seq)
AttributeError: 'MultipleSeqAlignment' object has no attribute 'add_sequence'

Does anybody have an idea what is wrong? Any help would be appreciated.
Thank you!

**Comment by tkchafin** [comment]
Hi, I can't replicate the issue -- can you check the version of BioPython 
In your terminal type "python3", which will open a python terminal (">>>"), then do the following: 
>>> import Bio
>>> Bio.__version__

**Comment by Irvilma** [comment]
Hi,

I'm working in an environmental folder created by conda in which I have python3. 

So, when I type the the command you write above, I get an error:
`python3`
Python 3.6.12 |Anaconda, Inc.| (default, Sep  8 2020, 17:50:39) 
[GCC Clang 10.0.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import Bio
>>> Bio.version
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'Bio' has no attribute 'version'
```

However, I installed biopyhton by conda, so if I type:
`conda list biopython`

I get the version (v1.79)

```
# packages in environment at /Applications/miniconda2/envs/py36:
#
# Name                    Version                   Build  Channel
biopython                 1.79             py36hfa26744_0    conda-forge
```

Thank you so much for your response! 
Irene

**Comment by Irvilma** [comment]
Ok,

I've just run the script on another computer and it worked!

I guess I have a problem with version compatibility.

Congratulations on your script and thanks for sharing it.

Irene
